Alias: $loinc = http://loinc.org
Alias: $icd-10 = http://hl7.org/fhir/sid/icd-10
Alias: $sct = http://snomed.info/sct
Alias: $sct-vs = http://snomed.info/sct?fhir_vs

Alias: $ucum = http://unitsofmeasure.org
Alias: $units-of-time = http://hl7.org/fhir/ValueSet/units-of-time

Alias: $address-type = http://hl7.org/fhir/address-type
Alias: $address-use = http://hl7.org/fhir/address-use
Alias: $audit-event-action = http://hl7.org/fhir/audit-event-action
Alias: $bodysite = http://hl7.org/fhir/ValueSet/body-site
Alias: $bodySite-condition = http://hl7.org/fhir/ValueSet/body-site
Alias: $clinical-findings = http://hl7.org/fhir/ValueSet/clinical-findings
Alias: $condition-clinical = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $condition-ver-status = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $condition-verification-status = http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $consent-action = http://terminology.hl7.org/CodeSystem/consentaction
Alias: $consent-provision-type = http://hl7.org/fhir/consent-provision-type
Alias: $consent-state-codes = http://hl7.org/fhir/consent-state-codes
Alias: $contact-point-system = http://hl7.org/fhir/contact-point-system
Alias: $degree-license-certificate = http://terminology.hl7.org/CodeSystem/v2-0360
Alias: $dhp-socioeconomic-cs = http://hl7.org/fhir/dhp/CodeSystem/socioeconomic-observation-usage
Alias: $dicom-dcm = http://dicom.nema.org/resources/ontology/DCM
Alias: $encounter-admit-source = http://terminology.hl7.org/CodeSystem/admit-source
Alias: $encounter-diagnosis-use = http://hl7.org/fhir/ValueSet/encounter-diagnosis-use
Alias: $encounter-discharge-disposition = http://terminology.hl7.org/CodeSystem/discharge-disposition
Alias: $encounter-status = http://hl7.org/fhir/encounter-status
Alias: $episode-of-care-status = http://hl7.org/fhir/episode-of-care-status
Alias: $extra-security-role-type = http://terminology.hl7.org/CodeSystem/extra-security-role-type
Alias: $fhir-types = http://hl7.org/fhir/fhir-types
Alias: $http-interaction = http://hl7.org/fhir/restful-interaction
Alias: $identifier-type = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $identifier-use = http://hl7.org/fhir/identifier-use
Alias: $imposeProfile = http://hl7.org/fhir/StructureDefinition/structuredefinition-imposeProfile
Alias: $iso-3166 = urn:iso:std:iso:3166
Alias: $issue-severity = http://hl7.org/fhir/issue-severity
Alias: $laterality = http://hl7.org/fhir/ValueSet/bodysite-laterality
Alias: $location-status = http://hl7.org/fhir/location-status
Alias: $m49.htm = http://unstats.un.org/unsd/methods/m49/m49.htm
Alias: $name-use = http://hl7.org/fhir/name-use
Alias: $object-role = http://terminology.hl7.org/CodeSystem/object-role
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category //http://hl7.org/fhir/observation-category
Alias: $observation-codes = http://hl7.org/fhir/ValueSet/observation-codes
Alias: $observation-dataAbsentReason = http://terminology.hl7.org/CodeSystem/data-absent-reason
Alias: $observation-interpretation = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $observation-methods = http://hl7.org/fhir/ValueSet/observation-methods
Alias: $observation-referencerange-normalvalue = http://hl7.org/fhir/observation-referencerange-normalvalue
Alias: $observation-status = http://hl7.org/fhir/observation-status
Alias: $organization-type-cs = http://terminology.hl7.org/CodeSystem/organization-type
Alias: $organization-type-vs = http://hl7.org/fhir/ValueSet/organization-type
Alias: $participant-type = http://terminology.hl7.org/CodeSystem/participant-type
Alias: $participation-role-type = http://terminology.hl7.org/CodeSystem/provenance-participant-type
Alias: $provenance-entity-role = http://hl7.org/fhir/provenance-entity-role
Alias: $provenance-participant-type = http://terminology.hl7.org/CodeSystem/provenance-participant-type
Alias: $qualification-codes = http://terminology.hl7.org/CodeSystem/v2-0360
Alias: $reference-meaning = http://terminology.hl7.org/CodeSystem/referencerange-meaning
Alias: $risk-probability-vs = http://hl7.org/fhir/ValueSet/risk-probability 
Alias: $risk-probability = http://terminology.hl7.org/CodeSystem/risk-probability
Alias: $sample-security-structural-codes = http://hl7.org/fhir/sample-security-structural-roles
Alias: $security-source-type = http://terminology.hl7.org/CodeSystem/security-source-type
Alias: $telecom-use = http://hl7.org/fhir/contact-point-use
Alias: $translation-extension = http://hl7.org/fhir/StructureDefinition/translation
Alias: $triggered-by-type = http://hl7.org/fhir/observation-triggeredbytype
Alias: $v2-0131 = http://terminology.hl7.org/CodeSystem/v2-0131
Alias: $v2-admission = http://terminology.hl7.org/CodeSystem/v2-0092
Alias: $v3-ActCode = http://terminology.hl7.org/CodeSystem/v3-ActCode
Alias: $v3-ActReason = http://terminology.hl7.org/CodeSystem/v3-ActReason
Alias: $v3-Confidentiality = http://terminology.hl7.org/CodeSystem/v3-Confidentiality
Alias: $v3-DocumentCompletion = http://terminology.hl7.org/CodeSystem/v3-DocumentCompletion
Alias: $v3-ObservationInterpretation = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $v3-MaritalStatus = http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
Alias: $v3-NullFlavor = http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $v3-obs-interpretation = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias: $v3-ParticipationType = http://terminology.hl7.org/CodeSystem/v3-ParticipationType
Alias: $v3-ParticipationType = http://terminology.hl7.org/CodeSystem/v3-ParticipationType
Alias: $v3-RoleClass = http://terminology.hl7.org/CodeSystem/v3-RoleClass
Alias: $v3-RoleCode = http://terminology.hl7.org/CodeSystem/v3-RoleCode 
Alias: $v3ActPriority = http://terminology.hl7.org/CodeSystem/v3-ActPriority
Alias: $valueset-supplement = http://hl7.org/fhir/StructureDefinition/valueset-supplement


// VitalSigns
Alias: $ucum-vitalsignsrate = http://hl7.org/fhir/ValueSet/ucum-vitalsignsrate
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category


// LtBase
Alias: $lt-patient = https://hl7.lt/fhir/base/StructureDefinition/lt-patient
Alias: $lt-practitioner = https://hl7.lt/fhir/base/StructureDefinition/lt-practitioner
Alias: $lt-practitioner-role = https://hl7.lt/fhir/base/StructureDefinition/lt-practitioner-role
Alias: $lt-organization = https://hl7.lt/fhir/base/StructureDefinition/lt-organization
Alias: $lt-encounter = https://hl7.lt/fhir/base/StructureDefinition/lt-encounter